FROM naartjie/alpine-lein-node

WORKDIR /src

# add deploy key for npm 'private' modules on github
COPY ./mimi/deploy.ssh /root/.ssh/
RUN chmod 600 /root/.ssh/*

# dependencies before code trick: http://bit.ly/1QfnlUR
COPY ./mimi/package.json /tmp/package.json
RUN cd /tmp && NODE_ENV=production npm install
RUN cp -a /tmp/node_modules /src/node_modules

RUN rm -rf /root/.ssh/

COPY ./mimi .

RUN lein cljsbuild once prod

EXPOSE 3000
CMD ["npm", "start"]
